CREATE TABLE comment (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
memId INT(6) NOT NULL,
authorNickname VARCHAR(50) NOT NULL,
authorPhoto VARCHAR(100) NOT NULL,
content VARCHAR(1000) NOT NULL,
dateTime VARCHAR(50) NOT NULL,
points INT(6) NOT NULL DEFAULT 0
) 